kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  serviceAccountName: nfs-client-provisioner
  nodeName: k8s-node2
  containers:
    - name: test-pod
      image: docker.io/library/busybox:latest
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "touch /mnt/SUCCESS && exit 0 || exit 1"
      volumeMounts:
        - name: nfs-pvc
          mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim