#NFS PV
apiVersion: v1              #接口名
kind: PersistentVolume		#创建PV
metadata:                   #基本信息
  name: nfs-pv    			#PV名称
  namespace: default        #命名空间
spec:                       #详细信息
  capacity:
    storage: 2Gi			#声明PV卷的容量大小
  accessModes:              #挂载策略
    # ReadWriteOnce 单节点,读/写 || ReadOnlyMany  多节点，只读 || ReadWriteMany 多节点，读/写
    - ReadWriteOnce
  # Retain（保留）手动回收，当pv不再使用，会处于等待状态
  # Recyle（回收）删除对应卷下所有内容
  # Delete（删除）直接删除固定存储资源
  persistentVolumeReclaimPolicy: Retain	#保留策略，Pod 删除后的策略
  storageClassName: nfs		#存储类的名称
  nfs:						#类的具体服务信息
    path: /root/nfsdata		#NFS存储服务器的共享目录
    server: 192.168.168.14	#NFS存储服务器的IP地址

---
#NFS PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce     #ReadWriteMany多主机读写
  storageClassName: "nfs"
  resources:
    requests:
      storage: 1Gi
